apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #ReadWriteMany, ReadOnlyMany
  gcePersistentDisk:
    pdName: pv-disc #nome do disco na cloud
  storageClassName: standard

