apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  resouces:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce #ReadWriteMany, ReadOnlyMany
  storageClassName: standard